#!/bin/bash

clear
pacman -Syu
pacman -S reflector --noconfirm --needed
pacman -S dialog --noconfirm --needed
pacman -S curl --noconfirm --needed
pacman -S xdg-user-dirs --noconfirm --needed
pacman -S git --noconfirm --needed
pacman -S wget --noconfirm --needed
pacman -S neofetch --noconfirm --needed
pacman -S lsb-release --noconfirm --needed

curl -LJO https://github.com/CodigoCristo/alvconf/archive/refs/heads/main.tar.gz
tar  -xvf alvconf-main.tar.gz
mv alvconf-main alvconf
cd alvconf
sh configurar

